modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="mended"
version="1.0"
displayName="Mended Mending"
credits="Original idea and code by Vazkii"
displayURL="https://curseforge.com/minecraft/mc-mods/mended-mending"
authors="tinytransfem"
logoFile="logo.png"
description='''Reworks the Mending enchantment to no longer break the gameplay loop.'''

[[dependencies.mended]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,]"
ordering="NONE"
side="BOTH"